-- Schema for "Banii mei" (ported 1:1 from the original SQLite schema).
-- Dates/months stay TEXT ('YYYY-MM' / ISO) so the app logic is unchanged.
-- Applied to Supabase project "buget-personal" on 2026-10-02.
create table settings (key text primary key, value text not null);
create table fx_rates (date text primary key, eur_ron double precision not null);
create table inflation_rates (period text primary key, rate double precision not null, source text not null, updated_at text not null);

create table categories (
  id integer generated by default as identity primary key,
  name text not null, kind text not null,
  bucket text not null default 'needs', color text not null default '#2E5C8A'
);
create unique index idx_categories_unique_name on categories (lower(trim(name)));

create table goals (
  id integer generated by default as identity primary key,
  name text not null, type text not null default 'goal',
  target double precision not null default 0, initial double precision not null default 0,
  deadline text, color text not null default '#C99A1E'
);

create table investments (
  id integer generated by default as identity primary key,
  name text not null, type text not null default 'ETF',
  expected_return double precision not null default 6
);

create table entries (
  id integer generated by default as identity primary key,
  month text not null, kind text not null,
  category_id integer references categories(id) on delete set null,
  goal_id integer references goals(id) on delete set null,
  investment_id integer references investments(id) on delete set null,
  description text not null default '', amount double precision not null,
  currency text not null default 'RON', recurring integer not null default 0
);
create index idx_entries_month on entries(month);

create table investment_values (
  investment_id integer not null references investments(id) on delete cascade,
  month text not null, value double precision not null,
  primary key (investment_id, month)
);

create table loans (
  id integer generated by default as identity primary key,
  name text not null, bank text not null default '',
  principal double precision not null, start_date text not null, term_months integer not null,
  schedule_type text not null default 'annuity',
  fixed_rate double precision not null default 0, fixed_months integer not null default 0,
  margin double precision not null default 0, ircc double precision not null default 0,
  fee_fixed_pct double precision not null default 0, fee_variable_pct double precision not null default 0,
  insurance_monthly double precision not null default 0,
  strategy text not null default 'term', active integer not null default 1,
  already_paid_principal double precision not null default 0,
  already_paid_interest double precision not null default 0
);

create table loan_prepayments (
  id integer generated by default as identity primary key,
  loan_id integer not null references loans(id) on delete cascade,
  month text not null, amount double precision not null,
  strategy text not null default 'term', note text not null default ''
);

create table loan_schedules (
  id integer generated by default as identity primary key,
  loan_id integer not null references loans(id) on delete cascade,
  month text not null, installment_nr integer not null,
  balance_start double precision not null, principal double precision not null,
  interest double precision not null, fee double precision not null default 0,
  payment double precision not null, balance_end double precision not null,
  is_paid integer not null default 0,
  unique (loan_id, installment_nr)
);
create index idx_loan_schedules_loan on loan_schedules(loan_id);

create table users (
  id integer generated by default as identity primary key,
  username text unique not null, password_hash text not null, salt text not null, created_at text not null
);

create table sessions (
  id text primary key,
  user_id integer not null references users(id) on delete cascade,
  created_at text not null, expires_at timestamptz not null
);
create index idx_sessions_expires on sessions(expires_at);

-- New for the online version: failed-login log used to throttle brute force.
create table login_attempts (
  id integer generated by default as identity primary key,
  ip text not null, attempted_at timestamptz not null default now()
);
create index idx_login_attempts on login_attempts(ip, attempted_at);

create table planned_purchases (
  id integer generated by default as identity primary key,
  name text not null, category text not null default 'Generale',
  total_price double precision not null, financing_type text not null default 'cash',
  down_payment double precision not null default 0, loan_term_months integer not null default 0,
  loan_interest_rate double precision not null default 0, target_date text,
  priority text not null default 'medie', notes text not null default '', created_at text not null
);

-- Lock everything down for the public Supabase API: RLS on, no policies,
-- and no grants for anon/authenticated. Only the server (bp_app role) reads/writes.
do $$
declare t text;
begin
  foreach t in array array['settings','fx_rates','inflation_rates','categories','goals','investments','entries',
    'investment_values','loans','loan_prepayments','loan_schedules','users','sessions','login_attempts','planned_purchases']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
  end loop;
end $$;

-- Dedicated least-privilege login role used by the Next.js server on Vercel.
-- (The real password lives only in Supabase and in the Vercel env var DATABASE_URL.)
-- create role bp_app with login password '<secret>' bypassrls;
grant usage on schema public to bp_app;
grant select, insert, update, delete on all tables in schema public to bp_app;
grant usage, select, update on all sequences in schema public to bp_app;
alter default privileges in schema public grant select, insert, update, delete on tables to bp_app;
alter default privileges in schema public grant usage, select, update on sequences to bp_app;
