-- Securizare: sesiuni salvate doar ca hash, passkey-uri (WebAuthn) obligatorii, coduri de recuperare,
-- reconfirmare pentru acțiuni sensibile, istoric de autentificare și blocare per cont.
-- Toate tabelele noi sunt „de sistem” (ca users/sessions): RLS activ, invizibile pentru API-ul public
-- Supabase (anon/authenticated), accesibile doar rolului serverului (bp_app).

-- 1. Sesiuni: în baza de date rămâne doar sha256(token). Cine ar citi tabela nu poate folosi valorile
--    ca să intre în cont. Sesiunile existente sunt convertite, deci nimeni nu e delogat.
update sessions set id = encode(sha256(convert_to(id, 'UTF8')), 'hex');
alter table sessions
  add column last_auth_at timestamptz,          -- ultima confirmare a identității (login / reconfirmare)
  add column last_seen_at timestamptz,
  add column ip text not null default '',
  add column user_agent text not null default '',
  add column location text not null default '',  -- oraș / țară aproximative (din headerele Vercel)
  add column method text not null default '';    -- password | passkey | recovery
update sessions set last_auth_at = created_at::timestamptz, last_seen_at = created_at::timestamptz;
create index if not exists idx_sessions_user on sessions(user_id);

-- 2. Blocare per cont (pe lângă cea per IP): rezistă și la încercări din multe IP-uri.
alter table users
  add column failed_logins integer not null default 0,
  add column locked_until timestamptz;

-- 3. Passkey-uri (WebAuthn). Cu cel puțin un passkey, parola singură nu mai deschide contul.
create table webauthn_credentials (
  id text primary key,                          -- credential ID (base64url)
  user_id integer not null references users(id) on delete cascade,
  public_key text not null,                     -- cheia publică COSE (base64url)
  counter bigint not null default 0,
  transports text not null default '',
  device_type text not null default '',
  backed_up integer not null default 0,
  name text not null default '',
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);
create index on webauthn_credentials(user_id);

-- Provocările WebAuthn în curs (valabile câteva minute, folosite o singură dată).
create table auth_challenges (
  id text primary key,                          -- sha256 al identificatorului din cookie
  user_id integer references users(id) on delete cascade,
  purpose text not null,                        -- login | register | reauth
  challenge text not null,
  expires_at timestamptz not null
);

-- 4. Coduri de recuperare (parolă + cod, dacă pierzi toate dispozitivele cu passkey). Doar hash-uri.
create table recovery_codes (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  code_hash text not null,
  created_at timestamptz not null default now(),
  used_at timestamptz
);
create index on recovery_codes(user_id);

-- 5. Istoric de autentificare (afișat în Setări → Securitate).
create table login_events (
  id integer generated by default as identity primary key,
  user_id integer references users(id) on delete cascade,
  success integer not null,
  method text not null default '',
  reason text not null default '',
  ip text not null default '',
  user_agent text not null default '',
  location text not null default '',
  created_at timestamptz not null default now()
);
create index on login_events(user_id, created_at desc);
create index on login_events(created_at);

do $$
declare t text;
begin
  foreach t in array array['webauthn_credentials','auth_challenges','recovery_codes','login_events']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant select, insert, update, delete on public.%I to bp_app', t);
    execute format('create policy server_all on public.%I for all to bp_app using (true) with check (true)', t);
  end loop;
end $$;
grant usage, select on all sequences in schema public to bp_app;
