-- Mai mulți utilizatori: conturi create pe bază de invitație, un administrator și un profil detaliat.
--
-- Datele financiare erau deja separate pe utilizator (0002_multi_user.sql). Aici adăugăm:
--   1. rolul de administrator (primul cont existent devine admin) și dezactivarea unui cont;
--   2. invitațiile: un link de o singură folosire, valabil 7 zile, din care se creează un cont nou;
--   3. profilul utilizatorului (date personale, ocupație și venit, obiective și profil de risc),
--      vizibil doar titularului (row-level security, ca restul datelor financiare).

-- 1. Administrator și conturi dezactivate
alter table users
  add column is_admin boolean not null default false,
  add column disabled_at timestamptz;

update users set is_admin = true where id = (select min(id) from users);

-- 2. Invitații (doar hash-ul codului ajunge în baza de date, ca la sesiuni)
create table invitations (
  id integer generated by default as identity primary key,
  token_hash text not null unique,
  note text not null default '',               -- pentru cine e (ex. „Maria”), doar ca reper pentru admin
  created_by integer references users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz,
  used_by integer references users(id) on delete set null,
  revoked_at timestamptz
);
create index on invitations(created_at desc);

alter table invitations enable row level security;
revoke all on invitations from anon, authenticated;
grant select, insert, update, delete on invitations to bp_app;
create policy server_all on invitations for all to bp_app using (true) with check (true);

-- 3. Profilul (un rând per utilizator, vizibil doar lui)
create table user_profiles (
  user_id integer primary key default nullif(current_setting('app.user_id', true), '')::integer
          references users(id) on delete cascade,
  -- Date personale
  first_name text not null default '',
  last_name text not null default '',
  birth_date text,                              -- YYYY-MM-DD
  city text not null default '',
  county text not null default '',
  email text not null default '',
  phone text not null default '',
  -- Ocupație și venit
  occupation text not null default '',          -- employee | self_employed | business | freelancer | retired | student | unemployed | other
  job_title text not null default '',
  income_stability text not null default '',    -- stable | variable
  net_income double precision,                  -- venit net lunar estimat (lei)
  payday integer check (payday between 1 and 31),
  currency text not null default 'RON',
  -- Obiective și profil de risc
  goals text not null default '',               -- listă separată prin virgulă: home, car, retirement, debt_free, ...
  risk_tolerance text not null default '',      -- low | medium | high
  horizon text not null default '',             -- short | medium | long
  investing_experience text not null default '',-- none | beginner | intermediate | advanced
  -- Ghidul de început
  onboarding_done_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table user_profiles enable row level security;
revoke all on user_profiles from anon, authenticated;
grant select, insert, update, delete on user_profiles to bp_app;
create policy own_rows on user_profiles for all to bp_app
  using (user_id = nullif(current_setting('app.user_id', true), '')::integer)
  with check (user_id = nullif(current_setting('app.user_id', true), '')::integer);

-- Conturile existente folosesc deja aplicația: nu le trimitem prin ghidul de început.
insert into user_profiles (user_id, onboarding_done_at) select id, now() from users;
