-- Lista de așteptare: emailurile lăsate pe site-ul de prezentare (leuta-landing-page), pe care
-- administratorul le vede în Administrare și le trimite invitații.
--
-- Datele se păstrează doar cât e nevoie (vezi Politica de confidențialitate a site-ului): rândul se
-- șterge când persoana își creează contul din invitație sau, cel târziu, la 12 luni de la înscriere
-- (curățenia o face cron-ul zilnic).

create table waitlist (
  id integer generated by default as identity primary key,
  email text not null unique,
  consent_version text not null,                -- versiunea textului de acord bifat în formular
  source text not null default 'landing',
  created_at timestamptz not null default now(),
  invited_at timestamptz,
  invitation_id integer references invitations(id) on delete set null
);
create index on waitlist(created_at desc);

-- Încercările de înscriere per IP (limitare anti-abuz); se șterg după o zi.
create table waitlist_attempts (
  ip text not null,
  attempted_at timestamptz not null default now()
);
create index on waitlist_attempts(ip, attempted_at);

do $$
declare t text;
begin
  foreach t in array array['waitlist','waitlist_attempts']
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('revoke all on public.%I from anon, authenticated', t);
    execute format('grant select, insert, update, delete on public.%I to bp_app', t);
    execute format('create policy server_all on public.%I for all to bp_app using (true) with check (true)', t);
  end loop;
end $$;
grant usage, select on all sequences in schema public to bp_app;
