-- Codurile de recuperare dispar: erau ușor de pierdut și blocau conturi. Cine își uită parola sau pierde
-- telefonul cu 2FA primește de la administrator un link de resetare (o singură folosire, valabil 24 de ore):
-- își alege o parolă nouă, iar 2FA și Face ID / amprenta se reactivează din Setări.
create table password_resets (
  id integer generated by default as identity primary key,
  user_id integer not null references users(id) on delete cascade,
  token_hash text not null unique,              -- sha256(cod); codul îl vede doar administratorul, o singură dată
  created_by integer references users(id) on delete set null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz,
  revoked_at timestamptz
);
create index on password_resets(user_id);

alter table password_resets enable row level security;
revoke all on password_resets from anon, authenticated;
grant select, insert, update, delete on password_resets to bp_app;
create policy server_all on password_resets for all to bp_app using (true) with check (true);
grant usage, select on all sequences in schema public to bp_app;

-- Hash-urile codurilor de recuperare nu mai folosesc la nimic (minimizarea datelor).
drop table recovery_codes;
alter table users drop column recovery_checked_at;
